### ISSUE TITLE
whats new/added

### ISSUE THREAD

**Issue by WMSGaming** [HausemasterIssue/spidersense#1]

**Comment by HausemasterIssue** [comment]
the client focuses more on 2b2t and strict servers, but it does have a few general improvements.
first, i removed bloat modules/code that nobody ever uses
second, i added criticals, with ncpstrict mode
i added better sprint, nofall, noslow (broken atm), better velocity, im working on silent swap in ca, and if you want more specific details just look at the changelog in releases :)

**Comment by WMSGaming** [comment]
Sounds good :)

**Comment by HausemasterIssue** [comment]
there is more stuff coming soon :)
