### ISSUE TITLE
what the actual shit

### ISSUE THREAD

**Issue by Sxmurai** [HausemasterIssue/spidersense#12]
i fork the client to try and fix shit i see wrong, and im getting 30 NPE's.

- One in VersionChecker (legit make a gist, ill do it for you and you can do it later)
- FastSwim. What the fuck is that???? (https://github.com/HausemasterIssue/spidersense/blob/master/src/main/java/com/gamesense/client/module/modules/movement/FastSwim.java#L109#L160)

The fastswim crashes on Dev startup

How the hell were you using it? 

Anyway, I'm making a PR soon with fixes

**Comment by HausemasterIssue** [comment]
let's just say im pretty retarded lmfao. fastswim gives you a null pointer exception, it's somewhere around like 113, i don't see any errors in eclipse, so im stuck on that. also the reason why i removed the link in the version checker is cuz i don't want my client connecting to github, or at least being able to check shit. 

yes please help me :pray: i really need your help with this, it's a miracle it even works at all kek.

**Comment by Sxmurai** [comment]
i already know whats wrong, im in the process of fixing the shit

**Comment by Sxmurai** [comment]
and removing the link in version checker throws a NPE, so i added a github gist.

you'll see what i mean when i make the pull request.

**Comment by Sxmurai** [comment]
check your email @HausemasterIssue

**Comment by HausemasterIssue** [comment]
i made a new contribute, fastprojectille from future beta has been leaked lmfao, cosmos added it so i pasted it, now i can one shot anyone LFMAO
