### ISSUE TITLE
nice work

### ISSUE THREAD

**Issue by master7720** [HausemasterIssue/spidersense#15]

**Comment by master7720** [comment]
you should makea discord for this

**Comment by HausemasterIssue** [comment]
thank you :3 

this is why i wont make a discord lol: https://www.youtube.com/watch?v=YJhW2BjFba0

and also cuz discord is autistic lol

**Comment by master7720** [comment]
lol okk

**Comment by HausemasterIssue** [comment]
> 
> 
> lol okk

also, i saw that you "deobfuscate" clients. may i reccomend using something like threadtear or a proper deobfuscator, then a good decompiler like cfr or something, you will get a lot farther :)
