### ISSUE TITLE
Is this yours?

### ISSUE THREAD

**Issue by Fiyxz** [HausemasterIssue/spidersense#17]
Or is it just stuff from Gamesence looks sorta the same lol.

**Comment by christallinqq** [comment]
bruhf

**Comment by HausemasterIssue** [comment]
SpiderSense is a continuation of GameSense. It has a LOT of new features. It shouldn't even be called a "skid" anymore, a continuation or "fork" would be more appropriate. It may look somewhat the same and is similar at it's core, but don't be fooled, it has MANY different and powerful features.
