### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by master7720** [HausemasterIssue/spidersense#20]
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

**Comment by HausemasterIssue** [comment]
bruh.

download the java 8 jdk and jre

install them

go to "edit user enviroment variables" in windows
add the variable "JAVA_HOME" and make it's location where u installed the jdk

then go in cmd

type

gradlew setupDecompWorkspace
gradlew clean
gradlew build

go in the builds -> libs folder and put the ,jar with the -release at the end of it in ur mods folder.
