### ISSUE TITLE
bug for ca

### ISSUE THREAD

**Issue by master7720** [HausemasterIssue/spidersense#28]
when i use the ca on 2b its works for like 7 secs then it stops idk if its a config issue or smt

**Comment by HausemasterIssue** [comment]
yeah thats your config. the biggest issue is see is the attack speed set at 20. you don't want it set at 20, on 2b you want to use 17-19 for attack speed, tho i personally recommend 19. also turn off cancel crystal, it can cause problems. also for place range on 2b you want that set to 4-4.5 and for walls range you want 3-3.5. put hitrange to 4-4.5 btw. here is my personal config that works good on 2b2t and strict servers:

{
  "Module": "AutoCrystal",
  "Settings": {
    "Target": "Smart",
    "Hand": "Main",
    "Type": "Swing",
    "Prioritise": "Damage",
    "Break": true,
    "Place": true,
    "Sequential": true,
    "AttackSpeed": 19,
    "HitRange": 4.4,
    "PlaceRange": 4.4,
    "WallsRange": 3.5,
    "EnemyRange": 6.0,
    "AntiWeakness": false,
    "AntiSuicide": true,
    "MinHealth": 14,
    "Switch": "Normal",
    "NoGapSwitch": true,
    "1.13Place": false,
    "CancelCrystal": false,
    "MinDamage": 4.0,
    "Limit": 1,
    "MinBreakDmg": 4.0,
    "MaxSelfDmg": 10.0,
    "FacePlaceHP": 8,
    "ArmourHealth%": 15,
    "FacePlaceDmg": 2.0,
    "Rotate": true,
    "Raytrace": false,
    "RenderDmg": false,
    "Outline": true,
    "HUD": "Target",
    "Color": 8191,
    "ForceWait": true,
    "Timeout(ms)": 10,
    "MaxTargets": 1
  }
}

**Comment by master7720** [comment]
ah ok thanks
