### ISSUE TITLE
things to add

### ISSUE THREAD

**Issue by master7720** [HausemasterIssue/spidersense#34]
auto32k
HoleBlocker
newchunks
mobowner
autowalk
safewalk
nuker
stashfinder
stashlogger
TpsSync
Chunkesp
PopChams

**Comment by HausemasterIssue** [comment]
cum

**Comment by master7720** [comment]
ikr

**Comment by master7720** [comment]
if you are gonna use popchams use wurst+3 popchams

**Comment by HausemasterIssue** [comment]
popchams are distracting

**Comment by master7720** [comment]
How?

**Comment by master7720** [comment]
fr fr

**Comment by master7720** [comment]
> popchams are fucking good looking, if you can get your hands on perry's phobos, people say his pop chams are good looking. not saying to skid them, but they could give some good ideas

i have seen it its fucking awesome perry makes the best renders
